### ISSUE TITLE
recommend a software called anki

### ISSUE THREAD

**Issue by asukaminato0721** [lxl66566/wordsreciter#1]
https://apps.ankiweb.net/

**Comment by lxl66566** [comment]
I used it once...and I can't accept it's mode(review every words after different periods) well

**Comment by asukaminato0721** [comment]
emmmm, actually it's called SRS( https://zh.wikipedia.org/wiki/间隔重复 ), and you can adjust the periods too. ( https://zhuanlan.zhihu.com/p/74599291 )

About how to write the card, Many articles are about it. https://static.kancloud.cn/ankigaokao/incremental_learning/2454060

**Comment by lxl66566** [comment]
OK, thanks a lot. I'll try it!

**Comment by lxl66566** [comment]
@wuyudi Excuse me, could you please recommend me some decks? I can't find decks that fit me with a few testing...
I have around 5500 words in my vocabulary (from preply.com) and a vague aim about living abroad (maybe(?))

**Comment by asukaminato0721** [comment]
There are many decks on anki website, but it's not good to "just" import them.

1. Use third part tools like https://saladict.crimx.com/anki.html to automate this procedure.(For example, when you are surfing a website.)
2. [Language Reactor](https://www.languagereactor.com/)
3. find a ready-made deck, then modify it to become your own deck.

---

some additional advice:

1. use https://github.com/open-spaced-repetition/fsrs4anki/ to reduce review amount.
2. feel free to use “on hold” (搁置) when repeatedly forget a word. So it won't generate so much pressure.

**Comment by wuyudi** [comment]
We are from the same university. :rofl:  (the library from your tg group)

**Comment by asukaminato0721** [comment]
You could contact me through my e-mail.

**Comment by lxl66566** [comment]
Thank you! Useful advices!
